apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-task-upload-file
  namespace: conductor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-task-upload-file
  template:
    metadata:
      labels:
        app: worker-task-upload-file
    spec:
      containers:
      - name: worker-task-upload-file
        image: sidharthjs/worker-task-upload-file:v1.0.13
        env:
        - name: CONDUCTOR_SERVER
          value: "http://conductor-server:8080/api"
        - name: BATCH_SIZE
          value: "1"