apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-task-write-to-db
  namespace: conductor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: worker-task-write-to-db
  template:
    metadata:
      labels:
        app: worker-task-write-to-db
    spec:
      containers:
      - name: worker-task-write-to-db
        # image: sidharthjs/worker-task-write-to-db:v1.0.13
        image: sidharthjs/worker-task-write-to-db:v2.0.9
        env:
        - name: CONDUCTOR_SERVER
          value: "http://conductor-server:8080/api"
        - name: BATCH_SIZE
          value: "1"