apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: vm-scaledobject-upload
  namespace: conductor
spec:
  minReplicaCount: 1
  pollingInterval: 10
  cooldownPeriod: 30
  maxReplicaCount: 12
  scaleTargetRef:
    name: worker-task-upload-file
  triggers:
  - type: prometheus
    metadata:
      # Required
      serverAddress: http://vmsingle-gravity.gravity-observability-system:8429
      metricName: task_queue_depth
      threshold: '3'
      query: task_queue_depth{taskType="upload_file"}
