apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaledobject-write-to-db
  namespace: conductor
spec:
  minReplicaCount: 0
  pollingInterval: 60
  cooldownPeriod: 30
  maxReplicaCount: 12
  scaleTargetRef:
    name: worker-task-write-to-db
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "3"
        url: "http://conductor-server.conductor:8080/api/tasks/queue/sizes?taskType=write_to_db"
        valueLocation: 'write_to_db'