apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: http-scaledobject-upload
  namespace: conductor
spec:
  minReplicaCount: 0
  pollingInterval: 60
  cooldownPeriod: 30
  maxReplicaCount: 12
  scaleTargetRef:
    name: worker-task-upload-file
  triggers:
    - type: metrics-api
      metadata:
        targetValue: "3"
        url: "http://conductor-server.conductor:8080/api/tasks/queue/sizes?taskType=upload_file"
        valueLocation: 'upload_file'