apiVersion: v1
kind: Service
metadata:
  name: svc-db-write-task-worker
  namespace: conductor
  labels:
    app: worker-task-write-to-db
spec:
  ports:
  - name: metrics
    port: 2112
    targetPort: 2112
    protocol: TCP
  selector:
    app: worker-task-write-to-db