apiVersion: v1
kind: Service
metadata:
  name: svc-upload-task-worker
  namespace: conductor
  labels:
    app: worker-task-upload-file
spec:
  ports:
  - name: metrics
    port: 2112
    targetPort: 2112
    protocol: TCP
  selector:
    app: worker-task-upload-file